[profile.default]
solc_version = '0.8.24'
src = 'contracts'
out = 'out'
libs = ['lib']
optimizer_runs = 200
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@forma-dev/sdk/=./',
    '@hyperlane-xyz/=node_modules/@hyperlane-xyz/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config